SELECT L.IDLIVROS AS ID_LIVROS,
L.TITULO, L.EDITORA AS NOME_EDITORA
FROM LIVROS L
ORDER BY L.EDITORA; 

SELECT A.NOME AS ASSUNTO,
L.TITULO
FROM LIVROS L 
JOIN ASSUNTOS A ON L.IDASSUNTO = A.IDASSUNTO
ORDER BY L.TITULO, A.NOME;

SELECT NOME AS NOME_AUTOR,
TITULO AS TITULO_LIVRO
FROM LIVROS L
JOIN AUTORIAS ON L.IDLIVROS = AUTORIAS.IDLIVROS 
JOIN AUTORES ON AUTORIAS.CODIGOAUTORES = AUTORES.CODIGOAUTORES
ORDER BY L.TITULO;


SELECT S.NOME AS SOCIOS
FROM SOCIOS S;

SELECT S.NOME AS SOCIOS,
S.CIDADE
FROM SOCIOS S
WHERE S.CIDADE = 'SOROCABA';

SELECT S.NOME AS SOCIOS,
S.CIDADE
FROM SOCIOS S
WHERE S.CIDADE != 'SOROCABA';


SELECT L.IDLIVROS AS ID_LIVROS,
L.TITULO,
S.NOME AS SOCIOS,
EMP.DTRETIRADA AS DATA_DE_RETIRADA
FROM LIVROS L 
JOIN EMPRESTIMOS EMP ON L.IDLIVROS = EMP.IDLIVROS
JOIN SOCIOS S ON EMP.CODSOCIO = S.CODSOCIO 
WHERE EMP.DTDEVREAL = NULL;

SELECT L.IDLIVROS AS ID_LIVROS,
L.TITULO,
S.NOME AS SOCIOS,
EMP.DTRETIRADA AS DATA_DE_RETIRADA,
EMP.DTDEVREAL AS DATA_DE_DEVOLUCAO_REAL,
EMP.VRMULTA AS VALOR_MULTA
FROM LIVROS L 
JOIN EMPRESTIMOS EMP ON L.IDLIVROS = EMP.IDLIVROS
JOIN SOCIOS S ON EMP.CODSOCIO = S.CODSOCIO 
WHERE EMP.DTDEVREAL > EMP.DTDEVPREV;

SELECT S.NOME AS SOCIOS,
       EMP.DTRETIRADA AS DATA_DE_RETIRADA,
       COUNT(*) AS QUANTIDADE_LIVROS
FROM EMPRESTIMOS EMP 
JOIN SOCIOS S ON EMP.CODSOCIO = S.CODSOCIO
WHERE EMP.DTRETIRADA = '10/10/24'
GROUP BY S.NOME, EMP.DTRETIRADA;


SELECT S.NOME AS SOCIOS,
EMP.DTRETIRADA AS DATA_DE_RETIRADA,
COUNT(*) AS QUANTIDADE_LIVROS
FROM EMPRESTIMOS EMP 
JOIN SOCIOS S ON EMP.CODSOCIO = S.CODSOCIO
WHERE EMP.DTRETIRADA = '10/10/24'
GROUP BY S.NOME, EMP.DTRETIRADA
HAVING COUNT(*) > 1;

SELECT L.IDLIVROS AS ID_LIVRO, AUTORES.NOME AS AUTORES,
COUNT(*) AS QUANTIDADE_AUTORES
FROM LIVROS L 
JOIN AUTORIAS ON L.IDLIVROS = AUTORIAS.IDLIVROS
JOIN AUTORES ON AUTORIAS.CODIGOAUTORES = AUTORES.CODIGOAUTORES
GROUP BY L.IDLIVROS, AUTORES.NOME;

SELECT SUM(EMP.VRMULTA) AS VALOR_TOTAL_MULTAS
FROM EMPRESTIMOS EMP; 

ALTER TABLE AUTORIAS RENAME COLUMN CODSOCIO TO CODIGOAUTORES;

