CREATE TABLE ASSUNTOS
(IDASSUNTO NUMBER(8) NOT NULL PRIMARY KEY,
NOME NVARCHAR2(80) NOT NULL UNIQUE );

CREATE TABLE LIVROS 
( IDLIVROS NVARCHAR2(15) NOT NULL ,
TITULO NVARCHAR2(80) NOT NULL,
EDITORA NVARCHAR2(20) NOT NULL,
TOTPAG NUMBER(4)CHECK(TOTPAG > 0),
DIASPRAZO NUMBER(3) CHECK(DIASPRAZO >=0),
IDASSUNTO NUMBER(8) NOT NULL,
CONSTRAINT PK_LIVRO PRIMARY KEY(IDTITULO),
CONSTRAINT FK_LIVRO_ASSUNTOS FOREIGN KEY(IDASSUNTO) REFERENCES ASSUNTOS(IDASSUNTO));