CREATE TABLE ASSUNTOS
(IDASSUNTO NUMBER(8) NOT NULL PRIMARY KEY,
NOME NVARCHAR2(80) NOT NULL UNIQUE );

CREATE TABLE LIVROS 
( IDLIVROS NVARCHAR2(15) NOT NULL ,
TITULO NVARCHAR2(80) NOT NULL,
EDITORA NVARCHAR2(20) NOT NULL,
TOTPAG NUMBER(4)CHECK(TOTPAG > 0),
DIASPRAZO NUMBER(3) CHECK(DIASPRAZO >=0),
IDASSUNTO NUMBER(8) NOT NULL,
CONSTRAINT PK_LIVRO PRIMARY KEY(IDLIVROS),
CONSTRAINT FK_LIVRO_ASSUNTOS FOREIGN KEY(IDASSUNTO) REFERENCES ASSUNTOS(IDASSUNTO));

CREATE TABLE EMPRESTIMOS 
(IDLIVROS NVARCHAR2(15) ,
CODSOCIO NUMBER(8),
DTRETIRADA DATE NOT NULL ,
DTDEVPREV DATE NOT NULL,
DTDEVREAL DATE,
VRMULTA FLOAT(2) CHECK(VRMULTA >=0),
CONSTRAINT PK_LIVRO_EMPRESTIMO PRIMARY KEY(IDLIVROS,CODSOCIO,DTRETIRADA),
CONSTRAINT FK_LIVRO_EMPRESTIMO FOREIGN KEY(IDLIVROS) REFERENCES LIVROS(IDLIVROS),
CONSTRAINT FK_SOCIOS_EMPRESTIMO FOREIGN KEY(CODSOCIO)REFERENCES SOCIOS(CODSOCIO));

CREATE TABLE SOCIOS 
(CODSOCIO NUMBER(8),
NOME NVARCHAR2(40) NOT NULL,
TELEFONE NVARCHAR2(20) NOT NULL,
LOGRADOURO NVARCHAR2(30) NOT NULL,
COMPLEM NVARCHAR2(15),
BAIRRO NVARCHAR2(15),
CIDADE NVARCHAR2(20),
UF NVARCHAR2(2),
CEP NVARCHAR2(8),
CONSTRAINT PK_SOCIOS PRIMARY KEY(CODSOCIO));


CREATE TABLE AUTORIAS
(IDLIVROS NVARCHAR2(15),
CODSOCIO NUMBER(8),
CONSTRAINT FK_LIVROS_AUTORAIS FOREIGN KEY(IDLIVROS) REFERENCES LIVROS(IDLIVROS),
CONSTRAINT FK_SOCIOS_AUTORAIS FOREIGN KEY(CODSOCIO)REFERENCES SOCIOS(CODSOCIO),
CONSTRAINT PK_AUTORAIS PRIMARY KEY(IDLIVROS,CODSOCIO));


CREATE TABLE AUTORES 
(CODIGOAUTORES NUMBER(8),
NOME NVARCHAR2(40) NOT NULL,
ORIGEM NVARCHAR2(20) NOT NULL,
CONSTRAINT PK_AUTORES PRIMARY KEY(CODIGOAUTORES));


INSERT INTO SOCIOS VALUES(1, 'CRISTIANE',NULL, NULL,NULL);
