CREATE TABLE FILIAIS(
CODIGO_FILIAL NVARCHAR2(1), NOME NVARCHAR2(15), TELEFONE NVARCHAR2(9),PRIMARY KEY (CODIGO_FILIAL));

CREATE TABLE CLIENTES( 
CODIGO NUMBER(2) NOT NULL, NOME NVARCHAR2(16), SEXO NVARCHAR2(1), LIMITE NUMBER(8,2), CODIGO_FILIAL NVARCHAR2(1),
PRIMARY KEY(CODIGO),
CONSTRAINT FK_CODIGO FOREIGN KEY (CODIGO_FILIAL) REFERENCES FILIAIS(CODIGO_FILIAL));

INSERT INTO FILIAIS VALUES('A','CENTRO', '3332-2020');
INSERT INTO FILIAIS VALUES('B','SHOPPING', '3333-1010');
INSERT INTO FILIAIS VALUES('C','VOTORANTIM','3243-1515');
INSERT INTO FILIAIS VALUES('D','ITU', '9321-8345');

INSERT INTO CLIENTES VALUES(5,'JOÃO','F','500','A');
INSERT INTO CLIENTES VALUES(28,'MARIA','F','300','C');
INSERT INTO CLIENTES VALUES(4,'PEDRO','M','700','A');
INSERT INTO CLIENTES VALUES(32,'PAULO','M','800','A');
INSERT INTO CLIENTES VALUES(16,'ANA','F','900','C');
INSERT INTO CLIENTES VALUES(15,'JOSÉ','M','500','B');
INSERT INTO CLIENTES VALUES(22,'ANTONIO','M','500',NULL);
INSERT INTO CLIENTES VALUES(19,'CLÁUDIA','F','900','B');

DELETE FROM CLIENTES WHERE CODIGO=16;
UPDATE CLIENTES SET CODIGO_FILIAL='B' WHERE CODIGO = 28; 
UPDATE CLIENTES SET CODIGO_FILIAL='B' WHERE CODIGO = 28;

DELETE FROM FILIAIS WHERE CODIGO_FILIAL='C';

INSERT INTO FILIAIS VALUES('E','SALTO', '8343-9483');

INSERT INTO CLIENTES VALUES(25,'ROBERTA','F','800','E');


UPDATE CLIENTES SET LIMITE=600 WHERE CODIGO = 5;
UPDATE CLIENTES SET LIMITE=400 WHERE CODIGO = 28;
UPDATE CLIENTES SET LIMITE=1000 WHERE CODIGO = 19;

SELECT * FROM CLIENTES;
